/* HATOCH HAMZA 
LAHCHIOUACH HASNA 
 BINOME 01 */

 --**********************Création de la base de données et contraintes d’intégrité***********************

--Q1:
CREATE TABLE DEPT (
    DEPTNO NUMBER(4),
    DNAME VARCHAR2(30),
    LOC VARCHAR2(30),
    ADD CONSTRAINT dept_dk PRIMARY KEY (DEPTNO),
    ADD CONSTRAINT dept_ck CHECK DNAME IN ('ACCOUNTING', 'RESEARCH', 'SALES','OPERATIONS'),
);

--Q2:
INSERT INTO DEPT VALUES (10,'ACCOUNTING','NEW-YORK');
INSERT INTO DEPT VALUES (20,'RESEARCH','DALLAS');
INSERT INTO DEPT VALUES (30,'SALES','CHICAGO');
INSERT INTO DEPT VALUES (40,'OPERATIONS','BOSTON');

--Q3:
CREATE TABLE EMP AS SELECT * FROM SCOTT.EMP;

--Q4:
 INSERT INTO EMP VALUES (7369, 'Bidon', NULL, NULL, NULL, NULL, NULL, NULL);
 --OUI LA REQUETE CI DESSOUS FONCTIONNE NORMAL.

 --Q5:
 ROLLBACK;

 --Q6:
 ALTER TABLE EMP ADD CONSTRAINT emp_pk PRIMARY KEY (EMPNO);
 ALTER TABLE EMP ADD CONSTRAINT emp_fk FOREIGN KEY (DEPTNO) REFERENCES DEPT (DEPTNO);

 --Q7:
 INSERT INTO EMP VALUES (7369, 'WILSON', 'MANAGER', 7839, '17/11/91', 3500.00, 600.00, 10) ;
 INSERT INTO EMP VALUES (7657, 'WILSON','MANAGER', 7839, '17/11/91', 3500.00, 600.00, 50) ; 
 INSERT INTO EMP VALUES(7657, 'WILSON', 'MANAGER', 7000,'17/11/91', 3500.00, 600.00, 10) ; 
 INSERT INTO EMP VALUES(7657, 'WILSON', 'MANAGER', 7839, '17/11/91', 3500.00,600.00, 10);
 --JE REMARQUE QUE LES 2 DERNIERS LIGNES NE PEUVENT PAS ETRE INSEREE PARCEQU'ELLES ONT 
 --LE MEME EMPNO QUI CONSTITUE LA CLE PRIMAIRE DU TABLEAU EMP

 --Q8:
 COMMIT;

 --**********************MISE A JOUR DE LA BD ***********************

 --Q1:
 UPDATE DEPT
 SET LOC='PITTSBURGH'
 WHERE DNAME='CHICAGO';
 

 --Q2:
 UPDATE EMP
 SET SAL=SAL*1.10
 WHERE COMM > SAL/2;

 --Q3:
 UPDATE EMP 
 SET COMM=AVG(NVL(COMM,0))
 WHERE HIREDATE < TO_DATE( '01/01/82','dd/mm/yy') AND COMM IS NULL ;

--Q4:
SAVEPOINT A;
ROLLBACK TO SAVEPOINT A;

--Q5:
DELETE FROM DEPT 
WHERE DEPTNO =20;
--UN ERREUR S'AFFICHE PUISQU'ON PEUT PAS SUPPRIMER UN DEPNO PUISQUE QU'IL EXISTE COMME CLE ETRANGERE DANS UNE AUTRE TABLE, POUR LE SUPPRIMER ON DOIT DESACTIVER LES CONTRAINTES D'INTEGRITE.


--**********************Interrogation de la base de données***********************

--Q1:
SELECT ENAME , SAL , COMM , SAL+COMM
FROM EMP
WHERE JOB ='SALESMAN';

--Q2:
SELECT ENAME 
FROM EMP 
ORDER BY COMM/SAL DESC;

--Q3:
SELECT ENAME 
FROM EMP 
WHERE COMM < 0.25*SAL;

--Q4:
SELECT COUNT(*)
FROM EMP
WHERE DEPTNO=10;

--Q5:
SELECT COUNT(*)
FROM EMP
WHERE COMM IS NOT NULL ;

--Q6:
SELECT COUNT(DISTINCT(JOB))
FROM EMP;

--Q7:
SELECT AVG(SAL)
FROM EMP 
GROUP BY JOB;

--Q8:
SELECT SUM(E.SAL)
FROM EMP E, DEPT D 
WHERE  E.DEPTNO = D.DEPTNO AND D.DNAME='SALES';

--Q9:
SELECT E.ENAME , D.DNAME
FROM EMP E , DEPT D
WHERE E.DEPTNO = D.DEPTNO ;

--Q10:
SELECT ENAME , JOB
FROM EMP 
WHERE SAL = (SELECT MAX(SAL) FROM EMP);

--Q11:
SELECT ENAME 
FROM EMP 
WHERE SAL > (
            SELECT SAL 
            FROM EMP 
            WHERE ENAME='JONES'
            );

--Q12:
SELECT ENAME 
FROM EMP
WHERE JOB = (
            SELECT JOB
            FROM EMP
            WHERE ENAME='JONES'
            );

--Q13:
SELECT ENAME
FROM EMP 
WHERE MGR = (SELECT MGR 
            FROM EMP 
            WHERE ENAME = 'CLARK ');

--Q14:
SELECT ENAME , JOB 
FROM EMP 
WHERE JOB = (SELECT JOB 
            FROM EMP 
            WHERE ENAME='TURNER')
AND  MGR=(SELECT MGR 
        FROM EMP 
        WHERE ENAME ='TURNER');


--Q15:
SELECT ENAME 
FROM EMP 
WHERE HIREDATE<ALL (SELECT HIREDATE 
                    FROM EMP 
                    WHERE DEPTNO=10);

--Q16:
SELECT E.ENAME,M.ENAME
FROM EMP E , EMP M 
WHERE E.EMPNO = M.EMPNO ;

--Q17:

SELECT E.ENAME
FROM EMP ENAME , EMP M
WHERE E.EMPNO = M.EMPNO and E.DEPTNO<>M.DEPTNO;
